sudo: required 
services: 
  -docker

before_instal:
  - docker build -t misinho7/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true misinho7/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker"
  env: "Docker-dev"
  bucket_name: "elasticbeanstalk-eu-north-1-176825653612"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESSS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"